
POST http://localhost:2001/feed/add
Content-Type: application/json

{
"url": "http://rss.cnn.com/rss/edition_africa.rss"
}

###

POST http://localhost:2001/feed/change
Content-Type: application/json

{
  "id": "83902672-622b-40eb-9ab5-d9e32669300c",
  "status": "active"
}


###

GET http://localhost:2001/feeds


###
DELETE http://localhost:2001/feeds/00bbe24d-1e7d-45fc-a294-96645f6d23a9

###

GET http://localhost:2001/fetch/a58599ff-c7ad-432e-87ef-82840d711cd0

###

GET http://localhost:2001/items?feedId=a58599ff-c7ad-432e-87ef-82840d711cd0&offset=10


###

GET http://localhost:2001/items